// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU7uQHQX1b8aykE7RGjo5-FJK01q0Ly4M',
    appId: '1:950907173796:web:80a82ac3b8b47b96cedf31',
    messagingSenderId: '950907173796',
    projectId: 'chat-app-b7462',
    authDomain: 'chat-app-b7462.firebaseapp.com',
    storageBucket: 'chat-app-b7462.firebasestorage.app',
    measurementId: 'G-VLC658CB76',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAruuY6h2ERbhAO7M5H7pIZa8M8u1f3hk',
    appId: '1:950907173796:ios:975ada0853627c08cedf31',
    messagingSenderId: '950907173796',
    projectId: 'chat-app-b7462',
    storageBucket: 'chat-app-b7462.firebasestorage.app',
    iosBundleId: 'com.example.studyMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAruuY6h2ERbhAO7M5H7pIZa8M8u1f3hk',
    appId: '1:950907173796:ios:975ada0853627c08cedf31',
    messagingSenderId: '950907173796',
    projectId: 'chat-app-b7462',
    storageBucket: 'chat-app-b7462.firebasestorage.app',
    iosBundleId: 'com.example.studyMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU7uQHQX1b8aykE7RGjo5-FJK01q0Ly4M',
    appId: '1:950907173796:web:5e20c85a00f0e669cedf31',
    messagingSenderId: '950907173796',
    projectId: 'chat-app-b7462',
    authDomain: 'chat-app-b7462.firebaseapp.com',
    storageBucket: 'chat-app-b7462.firebasestorage.app',
    measurementId: 'G-F15EVEKSJV',
  );

}